# Generated by Django 5.0.3 on 2024-04-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_pythoncourse_requestscourse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangocourse',
            old_name='video',
            new_name='video2',
        ),
        migrations.RenameField(
            model_name='pythoncourse',
            old_name='video',
            new_name='video1',
        ),
        migrations.RenameField(
            model_name='requestscourse',
            old_name='video',
            new_name='video3',
        ),
    ]
