# Generated by Django 5.0.3 on 2024-04-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_video_djangocourse_video2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangocourse',
            old_name='caption',
            new_name='caption2',
        ),
        migrations.RenameField(
            model_name='pythoncourse',
            old_name='caption',
            new_name='caption1',
        ),
        migrations.RenameField(
            model_name='requestscourse',
            old_name='caption',
            new_name='caption3',
        ),
    ]
